server:
  port: 8920
spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719

  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web    #如果ClassPath里没有kafka, active MQ, 默认是web http的方式
    sleuth:
      sampler:
        probability: 1.0  #100%取样，生产环境应该低一点,用不着全部取出来

  redis:
    host: localhost
    port: 6379

  #关闭thymeleaf缓存
  thymeleaf:
    cache: false

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    # 开启发送端消息抵达Broker确认
    publisher-confirm-type: correlated
    # 开启发送端消息抵达Queue确认
    publisher-returns: true
    template:
      # 只要消息抵达Queue，就会异步发送优先回调returnfirm
      mandatory: true
    listener:
      simple:
        # 手动ack消息，不使用默认的消费端确认
        acknowledge-mode: manual

#暴露全部监控接口
management:
  endpoints:
    web:
      exposure:
        include: "*"

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

##打开debug日志
logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.cloud.sleuth: DEBUG
