server:
  port: 8910
spring:
  application:
    name: gulimall-cart
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web    #如果ClassPath里没有kafka, active MQ, 默认是web http的方式
    sleuth:
      sampler:
        probability: 1.0  #100%取样，生产环境应该低一点,用不着全部取出来
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  #关闭thymeleaf缓存
  thymeleaf:
    cache: false

##打开debug日志
logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    com.zl52074.gulimall: debug

gulimall:
  thread:
    coreSize: 20
    maxSize: 20
    keepAliveTime: 10
