server:
  port: 8400
spring:
  application:
    name: gulimall-ware
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gulimall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    # 开启发送端消息抵达Broker确认
    publisher-confirm-type: correlated
    # 开启发送端消息抵达Queue确认
    publisher-returns: true
    template:
      # 只要消息抵达Queue，就会异步发送优先回调returnfirm
      mandatory: true
    listener:
      simple:
        # 手动ack消息，不使用默认的消费端确认
        acknowledge-mode: manual

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.zl52074.gulimall: debug

seata:
  enabled: true
  application-id: gulimall-ware
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: false
  service:
    vgroup-mapping:
      my_test_tx_group: default
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      application: seata-server
      group: SEATA_GROUP
